stages:
  - test
  - release
  - deploy

test_photographer:
  stage: test
  variables:
    MONGO_HOST: mongo-test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/photoapptest
  script:
    - cd app/photographer-service
    - pytest -p no:warnings
  services:
    - name: mongo:4.4.12
      alias: mongo-test

build_photographer:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json

  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/app/photographer-service"
      --dockerfile "${CI_PROJECT_DIR}/app/photographer-service/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/photographer:${CI_COMMIT_SHORT_SHA}"

deploy_photographer:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/photographer-service
    - sed -i "s/:latest/:${CI_COMMIT_SHORT_SHA}/g" k8s-photographer.yml
    - kubectl apply -f k8s-photographer.yml
  environment:
    name: production

test_photo:
  stage: test
  variables:
    MONGO_HOST: mongo-test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/photoapptest
  script:
    - cd app/photo-service
    - python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./proto/tags.proto
    - pytest -p no:warnings
  services:
    - name: mongo:4.4.12
      alias: mongo-service-test

build_photo:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
    
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json

  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/app/photo-service"
      --dockerfile "${CI_PROJECT_DIR}/app/photo-service/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/photo-service:${CI_COMMIT_SHORT_SHA}"


deploy_photo:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/photo-service
    - sed -i "s/:latest/:${CI_COMMIT_SHORT_SHA}/g" k8s-photo-service.yml
    - kubectl apply -f k8s-photo-service.yml
  environment:
    name: production



test_book:
  stage: test
  variables:
    MONGO_HOST: mongo-test
  image: $CI_REGISTRY/$CI_PROJECT_PATH/photoapptest
  script:
    - cd app/books-service
    - pytest -p no:warnings
  services:
    - name: mongo:4.4.12
      alias: mongo-test


build_book:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.gitlab.com\":{\"username\":\"gitlab-ci-token\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/app/books-service"
      --dockerfile "${CI_PROJECT_DIR}/app/books-service/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/book:${CI_COMMIT_SHORT_SHA}"


deploy_book:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
    - cd app/books-service
    - sed -i "s/:latest/:${CI_COMMIT_SHORT_SHA}/g" k8s-book.yml
    - kubectl apply -f k8s-book.yml
  environment:
    name: production
