# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tags.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tags.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntags.proto\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x19\n\tTagsReply\x12\x0c\n\x04tags\x18\x01 \x03(\t2.\n\x04Tags\x12&\n\x07getTags\x12\r.ImageRequest\x1a\n.TagsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=14
  _globals['_IMAGEREQUEST']._serialized_end=42
  _globals['_TAGSREPLY']._serialized_start=44
  _globals['_TAGSREPLY']._serialized_end=69
  _globals['_TAGS']._serialized_start=71
  _globals['_TAGS']._serialized_end=117
# @@protoc_insertion_point(module_scope)
