apiVersion: v1
kind: Service
metadata:
  name: k8s-photo-service
spec:
  selector:
    app: photo-service  # Correction pour correspondre au Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
        - name: photo-service
          image: gitlab-df-registry.imt-atlantique.fr/devops/devops-retake-01/photo-service:latest
          env:
            - name: DATABASE_NAME
              value: "devops-s23-xy-k8s-photo-db"
            - name: AUTH_DATABASE_NAME
              value: "devops-s23-xy-k8s-photo-db"
            - name: MONGO_HOST
              value: "mongo.cloud.rennes.enst-bretagne.fr"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

